### ISSUE TITLE
Code which compiles fine on v1.14.5 fails to compile with a cyclic dependency issue on v1.15

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#12726]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.15.0 (compiled with Erlang/OTP 24)

### Operating system

any

### Current behavior

Compiling the [TypeCheck](https://hex.pm/packages/type_check) library on Elixir v1.15.0, breaks with the following error:

```elixir
Compiling 115 files (.ex)
error: you are trying to use/import/require the module TypeCheck.Type which is currently being defined.

This may happen if you accidentally override the module you want to use. For example:

    defmodule MyApp do
      defmodule Supervisor do
        use Supervisor
      end
    end

In the example above, the new Supervisor conflicts with Elixir's Supervisor. This may be fixed by using the fully qualified name in the definition:

    defmodule MyApp.Supervisor do
      use Supervisor
    end

  lib/type_check.ex:142: TypeCheck.Type (module)


== Compilation error in file lib/type_check/internals/bootstrap.ex ==
** (CompileError) lib/type_check/type.ex: cannot compile module TypeCheck.Type (errors have been logged)
    expanding macro: TypeCheck.__using__/1
    lib/type_check/type.ex:8: TypeCheck.Type (module)
    (elixir 1.15.0) expanding macro: Kernel.use/1
    lib/type_check/type.ex:8: TypeCheck.Type (module)
    expanding macro: TypeCheck.Internals.Bootstrap.Macros.if_recompiling?/1
```

### Expected behavior

It should compile fine, as it did on versions up to and including Elixir v1.14.5.

---

Original issue on the TypeCheck repo: https://github.com/Qqwy/elixir-type_check/issues/185

---

I expect the problem has to do with the fact that the library is 'dogfooding' itself. Large parts of the library are compiled twice, allowing the compile-time checks which TypeCheck defines to be used inside TypeCheck's modules itself. Two simple macros ([in TypeCheck.Internals.Bootstrap.Macros](https://github.com/Qqwy/elixir-type_check/blob/main/lib/type_check/internals/bootstrap/macros.ex)) are used to make sure the compile-time checks are only added the second time the code is compiled, in that way keeping the cyclic dependencies in check.

My hypothesis is that some change related to the 'compile-time and boot time improvements' in v1.15.0, probably in what exactly happens as part of `Code.ensure_loaded`/`Code.ensure_compiled` which causes this code to break.

**Comment by josevalim** [comment]
Can you please provide a minimal case that reproduces the error?

**Comment by Qqwy** [comment]
The following minimal example reproduces the error: https://github.com/Qqwy/elixir-type_check-elixir-v1.15.0-error
by running `mix compile` (or `mix test`) in the project.

Here, the `Main` module should be compiled twice so it has access to its own compile-time functionality (in this case: a `__using__` that adds an extra function). The `bootstrap.ex` file ensures that the `Main` module is compiled twice. `main.ex` and `bootstrap.ex` use the two simple macros that can be found in `macros.ex` which are thin wrappers around `Code.ensure_compiled`, `Code.ensure_loaded` and `Code.compile_file`.

**Comment by josevalim** [comment]
Hi @Qqwy, I have looked at the project and I am honestly not sure we can guarantee compatibility to the project. It is doing something very unusual and a module requiring/importing itself should be a bug in 99.99% of the projects.

My suggestion is to to avoid importing/requiring yourself. This means the Builtin module has to be written exclusively with fully qualified names, but it should be doable. Here is a sample patch:

```diff
diff --git a/lib/type_check.ex b/lib/type_check.ex
index d67df27..3784ca4 100644
--- a/lib/type_check.ex
+++ b/lib/type_check.ex
@@ -136,11 +136,25 @@ defmodule TypeCheck do
         end

       _other ->
+        type_require =
+          if __CALLER__.module == TypeCheck.Type do
+            :ok
+          else
+            quote do: require(TypeCheck.Type)
+          end
+
+        builtin_import =
+          if __CALLER__.module == TypeCheck.Builtin do
+            :ok
+          else
+            quote do: import(TypeCheck.Builtin)
+          end
+
         quote generated: true, location: :keep do
           use TypeCheck.Macros, unquote(options)
           require TypeCheck
-          require TypeCheck.Type
-          import TypeCheck.Builtin
+          unquote(type_require)
+          unquote(builtin_import)
           :ok
         end
     end
diff --git a/lib/type_check/builtin.ex b/lib/type_check/builtin.ex
index dce7d15..a2098e2 100644
--- a/lib/type_check/builtin.ex
+++ b/lib/type_check/builtin.ex
@@ -1195,8 +1195,8 @@ defmodule TypeCheck.Builtin do
   if_recompiling? do
     @spec! guarded_by(
              type :: TypeCheck.Type.t(),
-             ast :: term(),
-             original_module :: module() | nil
+             ast :: TypeCheck.Builtin.Any.t(),
+             original_module :: TypeCheck.Builtin.Atom.t() | nil
            ) :: TypeCheck.Builtin.Guarded.t()
   end

@@ -1534,7 +1534,8 @@ defmodule TypeCheck.Builtin do
   because this would not respect the `@enforce_keys` option that might be given to structs.
   """
   if_recompiling? do
-    @spec! impl(protocol_name :: module()) :: TypeCheck.Builtin.ImplementsProtocol.t()
+    @spec! impl(protocol_name :: TypeCheck.Builtin.Atom.t()) ::
+             TypeCheck.Builtin.ImplementsProtocol.t()
   end

   def impl(protocol_name) when is_atom(protocol_name) do
```

**Comment by josevalim** [comment]
Here is a complete diff that fully compiles:

```diff
diff --git a/lib/type_check.ex b/lib/type_check.ex
index d67df27..3784ca4 100644
--- a/lib/type_check.ex
+++ b/lib/type_check.ex
@@ -136,11 +136,25 @@ defmodule TypeCheck do
         end
 
       _other ->
+        type_require =
+          if __CALLER__.module == TypeCheck.Type do
+            :ok
+          else
+            quote do: require(TypeCheck.Type)
+          end
+
+        builtin_import =
+          if __CALLER__.module == TypeCheck.Builtin do
+            :ok
+          else
+            quote do: import(TypeCheck.Builtin)
+          end
+
         quote generated: true, location: :keep do
           use TypeCheck.Macros, unquote(options)
           require TypeCheck
-          require TypeCheck.Type
-          import TypeCheck.Builtin
+          unquote(type_require)
+          unquote(builtin_import)
           :ok
         end
     end
diff --git a/lib/type_check/builtin.ex b/lib/type_check/builtin.ex
index dce7d15..5b855bc 100644
--- a/lib/type_check/builtin.ex
+++ b/lib/type_check/builtin.ex
@@ -362,7 +362,10 @@ defmodule TypeCheck.Builtin do
   c.f. `TypeCheck.Builtin.Function`
   """
   if_recompiling? do
-    @spec! function(param_types :: list(TypeCheck.Type.t()), return_type :: TypeCheck.Type.t()) ::
+    @spec! function(
+             param_types :: TypeCheck.Builtin.List.t(TypeCheck.Type.t()),
+             return_type :: TypeCheck.Type.t()
+           ) ::
              TypeCheck.Builtin.Function.t()
   end
 
@@ -628,7 +631,8 @@ defmodule TypeCheck.Builtin do
   C.f. `TypeCheck.Builtin.Tuple`
   """
   if_recompiling? do
-    @spec! fixed_tuple(types :: list(TypeCheck.Type.t())) :: TypeCheck.Builtin.FixedTuple.t()
+    @spec! fixed_tuple(types :: TypeCheck.Builtin.List.t(TypeCheck.Type.t())) ::
+             TypeCheck.Builtin.FixedTuple.t()
   end
 
   def fixed_tuple(list_of_element_types)
@@ -644,7 +648,8 @@ defmodule TypeCheck.Builtin do
   end
 
   if_recompiling? do
-    @spec! do_fixed_tuple(types :: list(TypeCheck.Type.t())) :: TypeCheck.Builtin.FixedTuple.t()
+    @spec! do_fixed_tuple(types :: TypeCheck.Builtin.List.t(TypeCheck.Type.t())) ::
+             TypeCheck.Builtin.FixedTuple.t()
   end
 
   defp do_fixed_tuple(element_types_list) do
@@ -664,7 +669,7 @@ defmodule TypeCheck.Builtin do
   For instance, `tuple(3)` is represented as `{any(), any(), any()}`.
   """
   if_recompiling? do
-    @spec! tuple(size :: non_neg_integer()) :: TypeCheck.Builtin.FixedTuple.t()
+    @spec! tuple(size :: TypeCheck.Builtin.NonNegInteger.t()) :: TypeCheck.Builtin.FixedTuple.t()
   end
 
   def tuple(0), do: fixed_tuple([])
@@ -711,7 +716,7 @@ defmodule TypeCheck.Builtin do
   C.f. `TypeCheck.Builtin.Literal`
   """
   if_recompiling? do
-    @spec! literal(a :: term()) :: TypeCheck.Builtin.Literal.t()
+    @spec! literal(a :: TypeCheck.Builtin.Any.t()) :: TypeCheck.Builtin.Literal.t()
   end
 
   def literal(value) do
@@ -745,7 +750,7 @@ defmodule TypeCheck.Builtin do
   c.f. `one_of/2`.
   """
   if_recompiling? do
-    @spec! one_of(types :: list(TypeCheck.Type.t())) :: TypeCheck.Type.t()
+    @spec! one_of(types :: TypeCheck.Builtin.List.t(TypeCheck.Type.t())) :: TypeCheck.Type.t()
   end
 
   def one_of(list_of_possibilities)
@@ -949,9 +954,10 @@ defmodule TypeCheck.Builtin do
 
   if_recompiling? do
     @spec fancy_map(
-            fixed_kvs :: list({term(), TypeCheck.Type.t()}),
-            required_kvs :: list({TypeCheck.Type.t(), TypeCheck.Type.t()}),
-            optional_kvs :: list({TypeCheck.Type.t(), TypeCheck.Type.t()})
+            fixed_kvs ::
+              TypeCheck.Builtin.List.t({TypeCheck.Builtin.Any.t(), TypeCheck.Type.t()}),
+            required_kvs :: TypeCheck.Builtin.List.t({TypeCheck.Type.t(), TypeCheck.Type.t()}),
+            optional_kvs :: TypeCheck.Builtin.List.t({TypeCheck.Type.t(), TypeCheck.Type.t()})
           ) ::
             TypeCheck.Builtin.CompoundFixedMap.t()
             | TypeCheck.Builtin.FixedMap.t()
@@ -1057,7 +1063,7 @@ defmodule TypeCheck.Builtin do
   and is thus represented as `[any()]` instead.
   """
   if_recompiling? do
-    @spec! fixed_list(element_types :: list(TypeCheck.Type.t())) ::
+    @spec! fixed_list(element_types :: TypeCheck.Builtin.List.t(TypeCheck.Type.t())) ::
              TypeCheck.Builtin.FixedList.t()
   end
 
@@ -1074,7 +1080,7 @@ defmodule TypeCheck.Builtin do
   end
 
   if_recompiling? do
-    @spec! do_fixed_list(element_types :: list(TypeCheck.Type.t())) ::
+    @spec! do_fixed_list(element_types :: TypeCheck.Builtin.List.t(TypeCheck.Type.t())) ::
              TypeCheck.Builtin.FixedList.t()
   end
 
@@ -1092,7 +1098,7 @@ defmodule TypeCheck.Builtin do
   c.f. `TypeCheck.Builtin.SizedBitstring`.
   """
   if_recompiling? do
-    @spec! sized_bitstring(prefix_size :: non_neg_integer()) ::
+    @spec! sized_bitstring(prefix_size :: TypeCheck.Builtin.NonNegInteger.t()) ::
              TypeCheck.Builtin.SizedBitstring.t()
   end
 
@@ -1134,7 +1140,10 @@ defmodule TypeCheck.Builtin do
   c.f. `TypeCheck.Builtin.SizedBitstring`.
   """
   if_recompiling? do
-    @spec! sized_bitstring(prefix_size :: non_neg_integer(), unit_size :: nil | 1..256) ::
+    @spec! sized_bitstring(
+             prefix_size :: TypeCheck.Builtin.NonNegInteger.t(),
+             unit_size :: nil | 1..256
+           ) ::
              TypeCheck.Builtin.SizedBitstring.t()
   end
 
@@ -1195,8 +1204,8 @@ defmodule TypeCheck.Builtin do
   if_recompiling? do
     @spec! guarded_by(
              type :: TypeCheck.Type.t(),
-             ast :: term(),
-             original_module :: module() | nil
+             ast :: TypeCheck.Builtin.Any.t(),
+             original_module :: TypeCheck.Builtin.Atom.t() | nil
            ) :: TypeCheck.Builtin.Guarded.t()
   end
 
@@ -1534,7 +1543,8 @@ defmodule TypeCheck.Builtin do
   because this would not respect the `@enforce_keys` option that might be given to structs.
   """
   if_recompiling? do
-    @spec! impl(protocol_name :: module()) :: TypeCheck.Builtin.ImplementsProtocol.t()
+    @spec! impl(protocol_name :: TypeCheck.Builtin.Atom.t()) ::
+             TypeCheck.Builtin.ImplementsProtocol.t()
   end
 
   def impl(protocol_name) when is_atom(protocol_name) do
diff --git a/mix.lock b/mix.lock
index abc84f5..2531b27 100644
--- a/mix.lock
+++ b/mix.lock
@@ -29,7 +29,7 @@
   "nimble_parsec": {:hex, :nimble_parsec, "1.2.3", "244836e6e3f1200c7f30cb56733fd808744eca61fd182f731eac4af635cc6d0b", [:mix], [], "hexpm", "c8d789e39b9131acf7b99291e93dae60ab48ef14a7ee9d58c6964f59efb570b0"},
   "parse_trans": {:hex, :parse_trans, "3.3.1", "16328ab840cc09919bd10dab29e431da3af9e9e7e7e6f0089dd5a2d2820011d8", [:rebar3], [], "hexpm", "07cd9577885f56362d414e8c4c4e6bdf10d43a8767abb92d24cbe8b24c54888b"},
   "specify": {:hex, :specify, "0.7.2", "328166d5ae9fe07dbca9e19cbe042fdaa7aaf289ef2fef7b0a5e03373e0da9bb", [:mix], [], "hexpm", "902605f3ecdfc8f763003f9eb202a923721eedc6a403b79e09771bfacd60750b"},
-  "ssl_verify_fun": {:hex, :ssl_verify_fun, "1.1.6", "cf344f5692c82d2cd7554f5ec8fd961548d4fd09e7d22f5b62482e5aeaebd4b0", [:make, :mix, :rebar3], [], "hexpm", "bdb0d2471f453c88ff3908e7686f86f9be327d065cc1ec16fa4540197ea04680"},
+  "ssl_verify_fun": {:hex, :ssl_verify_fun, "1.1.7", "354c321cf377240c7b8716899e182ce4890c5938111a1296add3ec74cf1715df", [:make, :mix, :rebar3], [], "hexpm", "fe4c190e8f37401d30167c8c405eda19469f34577987c76dde613e838bbc67f8"},
   "statistex": {:hex, :statistex, "1.0.0", "f3dc93f3c0c6c92e5f291704cf62b99b553253d7969e9a5fa713e5481cd858a5", [:mix], [], "hexpm", "ff9d8bee7035028ab4742ff52fc80a2aa35cece833cf5319009b52f1b5a86c27"},
   "stream_data": {:hex, :stream_data, "0.5.0", "b27641e58941685c75b353577dc602c9d2c12292dd84babf506c2033cd97893e", [:mix], [], "hexpm", "012bd2eec069ada4db3411f9115ccafa38540a3c78c4c0349f151fc761b9e271"},
   "tesla": {:hex, :tesla, "1.3.3", "26ae98627af5c406584aa6755ab5fc96315d70d69a24dd7f8369cfcb75094a45", [:mix], [{:castore, "~> 0.1", [hex: :castore, repo: "hexpm", optional: true]}, {:exjsx, ">= 3.0.0", [hex: :exjsx, repo: "hexpm", optional: true]}, {:fuse, "~> 2.4", [hex: :fuse, repo: "hexpm", optional: true]}, {:gun, "~> 1.3", [hex: :gun, repo: "hexpm", optional: true]}, {:hackney, "~> 1.6", [hex: :hackney, repo: "hexpm", optional: true]}, {:ibrowse, "~> 4.4.0", [hex: :ibrowse, repo: "hexpm", optional: true]}, {:jason, ">= 1.0.0", [hex: :jason, repo: "hexpm", optional: true]}, {:mime, "~> 1.0", [hex: :mime, repo: "hexpm", optional: false]}, {:mint, "~> 1.0", [hex: :mint, repo: "hexpm", optional: true]}, {:poison, ">= 1.0.0", [hex: :poison, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.4", [hex: :telemetry, repo: "hexpm", optional: true]}], "hexpm", "2648f1c276102f9250299e0b7b57f3071c67827349d9173f34c281756a1b124c"},
```

I will close this for now.
