### ISSUE TITLE
Compilation error when compiling :jsv — (RuntimeError) found error while checking types for JSV.Schema.xcast/1

### ISSUE THREAD

**Issue by simpers** [elixir-lang/elixir#15368]
### Elixir and Erlang/OTP versions

Erlang/OTP 28 [erts-16.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.20.0-rc.4 (9e4eb3d) (compiled with Erlang/OTP 28)

### Operating system

macOS

### Current behavior

Trying to update some dependencies, I came across this compilation issue trying to compile `:jsv` version `0.19.1`. Not sure if previous versions do compile or not, but it could be that this dependency didn't previously exist in the project I am bumping deps in, but the same version of `:jsv` does compile with 1.19.5-otp-28.

Creating the issue as prompted by the error message itself.

Compilation output with `:jsv` in the dependency tree:
```bash
$ mix compile
==> jsv
Compiling 72 files (.ex)

== Compilation error in file lib/jsv/schema.ex ==
** (RuntimeError) found error while checking types for JSV.Schema.xcast/1:

** (MatchError) no match of right hand side value:

    %{
      vars: %{
        0 => %{
          name: :caster,
          type: :term,
          context: nil,
          deps: %{},
          paths: [],
          off_traces: []
        }
      },
      warnings: [],
      failed: false,
      local_sigs: %{
        {:__struct__, 0} => {:def,
         {:infer, nil,
          [
            {[],
             %{
               map: {:closed,
                [
                  "$anchor": %{atom: {:union, %{nil: []}}},
                  "$comment": %{atom: {:union, %{nil: []}}},
                  "$defs": %{atom: {:union, %{nil: []}}},
                  "$dynamicAnchor": %{atom: {:union, %{nil: []}}},
                  "$dynamicRef": %{atom: {:union, %{nil: []}}},
                  "$id": %{atom: {:union, %{nil: []}}},
                  "$ref": %{atom: {:union, %{nil: []}}},
                  "$schema": %{atom: {:union, %{nil: []}}},
                  __struct__: %{atom: {:union, %{JSV.Schema => []}}},
                  additionalItems: %{atom: {:union, %{nil: []}}},
                  additionalProperties: %{atom: {:union, %{nil: []}}},
                  allOf: %{atom: {:union, %{nil: []}}},
                  anyOf: %{atom: {:union, %{nil: []}}},
                  contains: %{atom: {:union, %{nil: []}}},
                  contentEncoding: %{atom: {:union, %{nil: []}}},
                  ...
                ]}
             }}
          ]}, ...},
        ...
      },
      ...
    }

The exception happened while checking this code:

def (((xcast(caster) when :erlang.is_binary(caster)) when :erlang.is_atom(caster))
     when :erlang.is_binary(:erlang.hd(caster)))
    when :erlang.is_atom(:erlang.hd(caster)) do
  xcast(%{}, caster)
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

    (elixir 1.20.0-rc.4) lib/module/types/of.ex:98: Module.Types.Of.refine_body_var/5
    (elixir 1.20.0-rc.4) lib/module/types/helpers.ex:562: Module.Types.Helpers.zip_map_reduce/5
    (elixir 1.20.0-rc.4) lib/module/types/apply.ex:368: Module.Types.Apply.remote/8
    (elixir 1.20.0-rc.4) lib/module/types/pattern.ex:1045: anonymous fn/4 in Module.Types.Pattern.of_guards/3
    (elixir 1.20.0-rc.4) lib/enum.ex:1851: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.20.0-rc.4) lib/enum.ex:1851: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.20.0-rc.4) lib/module/types/pattern.ex:1044: Module.Types.Pattern.of_guards/3
    (elixir 1.20.0-rc.4) lib/module/types/pattern.ex:1030: Module.Types.Pattern.of_guards/4
could not compile dependency :jsv, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile jsv --force", update it with "mix deps.update jsv" or clean it with "mix deps.clean jsv"
```

### Expected behavior

As per the message, I was prompted to report the (possible) bug.

**Comment by josevalim** [comment]
Thank you! It has been fixed in main (duplicate of #15358).

**Comment by simpers** [comment]
Gosh, I tried to find if it had already been reported! 😅 Thanks for the quick work! And a new RC to try as well
