### ISSUE TITLE
Compilation error for floki on main

### ISSUE THREAD

**Issue by moomerman** [elixir-lang/elixir#15359]
### Elixir and Erlang/OTP versions

While testing out the fix for #15358 on main, I'm getting an error compiling floki.  Compiles fine with 1.19.5.

```
Erlang/OTP 28 [erts-16.3.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.20.0-rc.4 (8a2c815) (compiled with Erlang/OTP 28)
```

### Operating system

macOS

### Current behavior

`MIX_OS_DEPS_COMPILE_PARTITION_COUNT=1 mix compile`

```
==> floki
Compiling 2 files (.erl)
Compiling 30 files (.ex)

== Compilation error in file lib/floki.ex ==
** (RuntimeError) found error while checking types for Floki.children/1:

** (FunctionClauseError) no function clause matching in Module.Types.add_inferred/5
The exception happened while checking this code:

def children(x0) do
  super(x0, include_text: true)
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

    (elixir 1.20.0-rc.4) lib/module/types.ex:507: Module.Types.add_inferred([], [%{atom: {:negation, %{}}, list: {46675407, :term, :term}, map: {61102469, :open, []}, fun: {:negation, %{}}, tuple: {2985101174, {-59496799, :closed, [:term, :term, :term]}, :bdd_bot, :bdd_bot, {61102469, :open, []}}, bitmap: 255}], %{atom: {:union, %{nil: []}}}, 0, [{[%{tuple: {-59496799, :closed, [:term, :term, :term]}}], %{dynamic: :term}}])
    (elixir 1.20.0-rc.4) lib/module/types.ex:374: anonymous fn/7 in Module.Types.default_local_handler/9
    (elixir 1.20.0-rc.4) lib/enum.ex:2622: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.20.0-rc.4) lib/module/types.ex:364: Module.Types.default_local_handler/9
    (elixir 1.20.0-rc.4) lib/module/types.ex:306: Module.Types.local_handler/5
    (elixir 1.20.0-rc.4) lib/module/types.ex:86: anonymous fn/5 in Module.Types.infer/7
    (elixir 1.20.0-rc.4) lib/enum.ex:2622: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.20.0-rc.4) lib/module/types.ex:78: Module.Types.infer/7
```

### Expected behavior

floki compiles
