### ISSUE TITLE
Compiler reports deadlock for %__MODULE__{} instead of struct undefined error 

### ISSUE THREAD

**Issue by antipax** [elixir-lang/elixir#5053]
```elixir
# test.ex
defmodule Deadlock do
  def deadlock do
    %__MODULE__{}
  end
end
```

```
╰─$ elixirc test.ex

== Compilation error on file test.ex ==
** (CompileError)  deadlocked waiting on module Deadlock

Compilation failed because of a deadlock between files.
The following files depended on the following modules:

  test.ex => Deadlock

```

in IEx, where the parallel compiler is unused:
```elixir
iex(1)> defmodule Deadlock do
...(1)>   def deadlock do
...(1)>     %__MODULE__{}
...(1)>   end
...(1)> end
** (CompileError) iex:3: Deadlock.__struct__/1 is undefined, cannot expand struct Deadlock
```

So it seems like, in order to provide an accurate error, this is maybe a special case that needs to/should be handled by the parallel compiler?

**Comment by josevalim** [comment]
Could this have been caused by b98b4bd235ccf461c49d7218a9614d34df94bfdb?

**Comment by josevalim** [comment]
Actually, I misunderstood the issue. It is mostly a matter of knowing the struct won't be defined if I am trying to access the module itself. :) I don't think it was necessarily caused by above (and if it was, it doesn't matter much).

**Comment by antipax** [comment]
Working on this, let me know if anyone has an objection.

**Comment by michalmuskala** [comment]
Is this related?
```elixir
defmodule Test do
  require Test
end
```

```
== Compilation error on file test.exs ==
** (CompileError)  deadlocked waiting on module Test
    (elixir) src/elixir_aliases.erl:80: :elixir_aliases.ensure_loaded/3

Compilation failed because of a deadlock between files.
The following files depended on the following modules:

  test.exs => Test

```

**Comment by antipax** [comment]
I would argue that message is at least accurate, though it of course could be improved to say what the problem is more directly. I'm not sure it would be worth it, though.

**Comment by josevalim** [comment]
@antipax one option is to discard the current patch and instead change the parallel compiler to raise a better error when I am waiting on myself. This would solve both issues.

**Comment by whatyouhide** [comment]
Actually I am 👍 on @josevalim's suggestion, it's a bit like when we say "function undefined or private", so that we don't have to do too many stuff an can just give an error message that explains possible causes.

**Comment by antipax** [comment]
Doesn't the current message already say that it is waiting on itself? I don't think that makes the error more clear in the struct situation.

**Comment by antipax** [comment]
To be clear, I think we should do both. The error message for deadlocked on self could be improved. The error message for an undefined local struct should say undefined struct, not deadlocked on self, IMO, because the fact that it produces a deadlock at all instead of a undefined error is due to an implementation detail (since structs can be waited on in the parallel compiler).

**Comment by antipax** [comment]
So, has anyone come to any conclusions on this? Happy to close this out whatever way you all want to.

**Comment by josevalim** [comment]
@antipax I would prefer to solve the problem generally first, if possible, and then merge the current patch only if necessary.

**Comment by antipax** [comment]
@josevalim Ok, what kinda message are you thinking to display when we are waiting on ourselves?

**Comment by josevalim** [comment]
@antipax I am not even sure if we can generally detect if we are waiting on ourselves. Can we? If so, we should just ask it to proceed (we could lie the module is available) because then it will certainly crash afterwards.

**Comment by antipax** [comment]
@josevalim I'm not sure, that's an interesting idea though and would solve the problem very cleanly. I will investigate.
