### ISSUE TITLE
Compiler crash when validating struct types

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#10784]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 23 [erts-11.1.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Operating system: osx 10.15.7

### Current behavior

During refactoring of an umbrella app I was extracting some modules to a helper library (path dep in mix). I renamed Umbrella.Child.MyStruct to MyLib.MyStruct and hit `mix compile`.
The compiler crashed with:
```
Compiling 16 files (.ex)
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for Umbrella.Child.Some.fun/2

(source omitted)


Please report this bug: https://github.com/elixir-lang/elixir/issues

** (UndefinedFunctionError) function Umbrella.Child.MyStruct.__struct__/0 is undefined (module Umbrella.Child.MyStruct is not available)
        Umbrella.Child.MyStruct.__struct__()
        (elixir 1.11.3) lib/module/types/of.ex:101: Module.Types.Of.struct/3
        (elixir 1.11.3) lib/module/types/pattern.ex:552: Module.Types.Pattern.of_shared/4
        (elixir 1.11.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.3) lib/module/types/pattern.ex:535: Module.Types.Pattern.of_shared/4
        (elixir 1.11.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.3) lib/module/types/pattern.ex:535: Module.Types.Pattern.of_shared/4
        (elixir 1.11.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
```

After `mix clean` the error was no longer reproducible.

I can open a PR adding a `function_exported` check in https://github.com/elixir-lang/elixir/blob/1e81a5b9a5e4cbf59179a5cd93f0bf48f803283f/lib/elixir/lib/module/types/of.ex#L101 but I believe there's a staleness issue somewhere and by doing that we'll just hide it.

**Comment by josevalim** [comment]
Thanks for the report! Can you please try master or provide a mechanism to reproduce the error? We had issues related to this and the root cause is Mix not recompiling all relevant modules. But it should be fixed in master. In case it is still faulty, the bug is in Mix, not the checker. :)

**Comment by lukaszsamson** [comment]
I can try that later.

**Comment by lukaszsamson** [comment]
@josevalim I was able to reproduce this bug on both 1.11 and current master. On 1.11 all it takes is to comment out the struct module. On master commenting out is not sufficient as it picks up file modification but file delete reproduces it reliably.

1. clone https://github.com/lukaszsamson/elixir_type_checker_crash_repro
2. `mix compile`
```
Compiling 3 files (.ex)
Generated type_checker_crash app
```
3. `mv lib/some_struct.ex lib/some_struct.ex` to simulate delete
4. introduce a compilation error in lib/type_checker_crash.ex (e.g. delete the closing `}` in hello
5. `mix compile`
```
Compiling 1 file (.ex)

== Compilation error in file lib/type_checker_crash.ex ==
...
```
6. fix the error
7. `mix compile`
```
Compiling 1 file (.ex)
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for TypeCheckerCrash.Some.process/2
...
```

If you on the other hand I omit the compile error steps (4-6) then the compilation finishes without the crash. Note that the file using the deleted struct is not recompiled.
3. `mv lib/some_struct.ex lib/some_struct.ex` to simulate delete
4a. `mix compile`
```
Generated type_checker_crash app
```

**Comment by lukaszsamson** [comment]
I've just seen another case of that error on elixir 1.12.3. I'm not really sure what I did to trigger it as I switched branches, did mix deps.get after upgrading elixir from 1.12.2 to 1.12.3. This time there were no deletes involved. Both the checked module and the struct that caused the crash are present on both branches and haven't changed in a long time. I wasn't able to find a repro though.

```
an exception was raised:
    ** (Module.Types.Error) found error while checking types for MyApp.SomeGrid.filter_range/2

def(filter_range(dynamic_exp, %MyApp.Grid.Filters.TimeRange{} = range)) do
  %Ecto.Query.DynamicExpr{fun: fn query ->
    _ = query
    {{:and, [], [{:^, [], [0]}, {:^, [], [1]}]}, [{filter_range_min(dynamic_exp, range.start), :boolean}, {filter_range_max(dynamic_exp, range.end), :boolean}], []}
  end, binding: [], file: "/some_path.ex", line: 4}
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (UndefinedFunctionError) function MyApp.Grid.Filters.TimeRange.__struct__/0 is undefined (module MyApp.Grid.Filters.TimeRange is not available)
        (myapp 0.0.1) MyApp.Grid.Filters.TimeRange.__struct__()
        (elixir 1.12.3) lib/module/types/of.ex:131: Module.Types.Of.struct/3
        (elixir 1.12.3) lib/module/types/pattern.ex:517: Module.Types.Pattern.of_shared/4
        (elixir 1.12.3) lib/module/types/pattern.ex:47: Module.Types.Pattern.of_pattern/3
        (elixir 1.12.3) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.12.3) lib/module/types/pattern.ex:12: Module.Types.Pattern.of_head/4
        (elixir 1.12.3) lib/module/types.ex:62: Module.Types.warnings_from_clause/6
        (elixir 1.12.3) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5
        (elixir 1.12.3) lib/enum.ex:3900: Enum.flat_map_list/2
        (elixir 1.12.3) lib/enum.ex:3901: Enum.flat_map_list/2
        (elixir 1.12.3) lib/enum.ex:3900: Enum.flat_map_list/2
        (elixir 1.12.3) lib/enum.ex:3901: Enum.flat_map_list/2
        (elixir 1.12.3) lib/module/parallel_checker.ex:104: Module.ParallelChecker.check_module/2
        (elixir 1.12.3) lib/module/parallel_checker.ex:300: anonymous fn/5 in Module.ParallelChecker.spawn_checkers/1
```

For reference similar issues https://github.com/elixir-lang/elixir/issues/10584 https://github.com/elixir-lang/elixir/issues/10535

**Comment by josevalim** [comment]
If the struct is meant to be there, then this certainly shouldn't happen!
