### ISSUE TITLE
Compilation fails: undefined function defdelegate/2

### ISSUE THREAD

**Issue by dmorneau** [elixir-lang/elixir#10877]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.0-rc.0 (31d2b99) (compiled with Erlang/OTP 24)
* Operating system: macOS

### Current behavior

This library builds on 1.11.4 but fails on 1.12.0-rc0:

https://github.com/tompave/fun_with_flags/blob/master/lib/fun_with_flags/protocols/actor.ex#L117

```
== Compilation error in file lib/fun_with_flags/protocols/actor.ex ==
** (CompileError) lib/fun_with_flags/protocols/actor.ex:117: undefined function defdelegate/2
```

### Expected behavior

Build on 1.12.0-rc0. I don't see any deprecation or changes related to defdelegate in release notes.

**Comment by josevalim** [comment]
The feature being used there is unsupported as you can't have function definitions inside protocols. I will revert this change for v1.12 but I recommend opening an issue on fun_with_flags so it is fixed on later releases. If they really want to keep it, they can call `Kernel.defdelegate` instead, but I don't recommend. :) Thank you for the report!

**Comment by dmorneau** [comment]
Will do. Thank you!

**Comment by tompave** [comment]
I'm the owner of `fun_with_flags`.
Thank you for reporting this here and on the package issues (https://github.com/tompave/fun_with_flags/issues/104). This will be fixed soon. 👍
