### ISSUE TITLE
Type checking error with latest optimizations

### ISSUE THREAD

**Issue by SteffenDE** [elixir-lang/elixir#14621]
### Elixir and Erlang/OTP versions

Latest main, commit b29c83a42f12fef5f861f734bd916d815f46c87c.

### Operating system

macOS

### Current behavior

Introduced by b29c83a42f12fef5f861f734bd916d815f46c87c.

```
== Compilation error in file lib/phoenix_component/macro_component.ex ==
** (RuntimeError) found error while checking types for Phoenix.Component.MacroComponent.build_ast/2:

** (RuntimeError) found error while checking types for Phoenix.Component.MacroComponent.build_ast/4:

** (RuntimeError) found error while checking types for Phoenix.Component.MacroComponent.token_attrs_to_ast/2:

** (MatchError) no match of right hand side value:

    true
The exception happened while checking this code:

defp token_attrs_to_ast(attrs, env) do
  Enum.map(attrs, fn {name, value, _meta} ->
    case :erlang.==(name, :root) do
      false ->
        nil

      true ->
        format_attr = fn
          {:string, binary, _meta} -> binary
          {:expr, code, _meta} -> code
          nil -> "nil"
        end

        :erlang.error(
          ArgumentError.exception(
            <<"dynamic attributes are not supported in macro components, got: ",
              String.Chars.to_string(format_attr.(value))::binary>>
          )
        )
    end

    case value do
      {:string, binary, _meta} ->
        {name, binary}

      {:expr, code, meta} ->
        ast = Code.string_to_quoted!(code, line: meta.line, column: meta.column, file: env.file)
        {name, ast}

      nil ->
        {name, nil}
    end
  end)
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

defp build_ast([{:tag, name, attrs, %{closing: type}} | rest], acc, stack, env)
     when :erlang.orelse(:erlang."=:="(type, :self), :erlang."=:="(type, :void)) do
  acc = [{name, token_attrs_to_ast(attrs, env), [], %{closing: type}} | acc]
  build_ast(rest, acc, stack, env)
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

def build_ast([{:tag, name, attrs, tag_meta} | rest], env) do
  case closing = tag_meta[:closing] do
    x when :erlang.orelse(:erlang."=:="(x, false), :erlang."=:="(x, nil)) -> nil
    _ -> true = :erlang.orelse(:erlang."=:="(closing, :self), :erlang."=:="(closing, :void))
  end

  meta = Map.take(tag_meta, [:closing])
  build_ast(rest, [], [{name, token_attrs_to_ast(attrs, env), meta}], env)
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

    (elixir 1.20.0-dev) lib/module/types/descr.ex:1498: Module.Types.Descr.phi/4
    (elixir 1.20.0-dev) lib/module/types/descr.ex:1510: anonymous fn/5 in Module.Types.Descr.phi/4
    (elixir 1.20.0-dev) lib/enum.ex:5018: Enumerable.List.reduce/3
    (elixir 1.20.0-dev) lib/enum.ex:2574: Enum.reduce_while/3
    (elixir 1.20.0-dev) lib/module/types/descr.ex:1505: Module.Types.Descr.phi/4
    (elixir 1.20.0-dev) lib/module/types/descr.ex:1478: Module.Types.Descr.phi_starter/3
    (elixir 1.20.0-dev) lib/enum.ex:4307: Enum.predicate_list/3
    (elixir 1.20.0-dev) lib/module/types/descr.ex:484: Module.Types.Descr.iterator_empty_difference_subtype?/2
```

### Expected behavior

Works fine on the previous commit d7bdea55de980822765a4ed8609589747a6df53d.
