### PR TITLE
Support module attributes in remote types

### LINKED ISSUE #4874: invalid remote in typespec: @for.t() for typespec inside defimpl
### Environment

* Elixir version (elixir -v): 1.3.0
* Operating system: OSX 10.11.5

1. `git clone https://github.com/C-S-D/alembic`
2. `git checkout 565ad837d4664075a88b37eb9f277e6d450904dd`
3. `mix compile`

### Current behavior

[Alembic](https://github.com/C-S-D/alembic) fails to compile under Elixir 1.3.0.  (It compiled and passed `mix dialyze` without errors under 1.2.6 [[CircleCI Build](https://circleci.com/gh/C-S-D/alembic/107)]).  It stops complication because it can't resolve [`@for.t` in `Alembic.Source`'s `Poison.Encoder`](https://github.com/C-S-D/alembic/blob/565ad837d4664075a88b37eb9f277e6d450904dd/lib/alembic/source.ex#L261):

```
==> alembic
Compiling 20 files (.ex)

== Compilation error on file lib/alembic/source.ex ==
** (CompileError) lib/alembic/source.ex:261: invalid remote in typespec: @for.t()
    (elixir) lib/kernel/typespec.ex:981: Kernel.Typespec.compile_error/2
    (elixir) lib/kernel/typespec.ex:871: Kernel.Typespec.typespec/3
    (elixir) lib/kernel/typespec.ex:1009: anonymous fn/4 in Kernel.Typespec.fn_args/4
    (elixir) lib/enum.ex:1622: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/kernel/typespec.ex:1009: Kernel.Typespec.fn_args/4
    (elixir) lib/kernel/typespec.ex:998: Kernel.Typespec.fn_args/5
    (elixir) lib/kernel/typespec.ex:461: Kernel.Typespec.translate_spec/7
```

### Expected behavior

`@for.t` is expanded to `Alembic.Source.t` and compilation continues.

### PR DESCRIPTION
**Pull request by whatyouhide**
For example, `@for.t` in protocols or similar use cases. This PR closes #4874.

I'm open to feedback on the error message we should give if the module attribute doesn't expand to a module :)

For the record, this was broken in https://github.com/elixir-lang/elixir/commit/a3c429f9b9a476f995b23328430a1dcca55d1799, when we stopped expanding module attributes in `Macro.expand_once/2`.

### CODE REVIEW

File: lib/elixir/lib/kernel/typespec.ex [hunk 1]
```diff
@@ -864,6 +864,19 @@ defmodule Kernel.Typespec do
     {:op, line(meta), op, {:integer, line(meta), integer}}
   end
 
+  # Handle remote calls in the form of @module_attribute.type.
```
Comment (eksperimental) [inline lib/elixir/lib/kernel/typespec.ex]: `can we use backticks? Since its touching a "." @module_attribute.type`

Comment (whatyouhide) [inline lib/elixir/lib/kernel/typespec.ex]: I am not 100% sure yet but I lean on thinking backticks in comments are not a good thing. Also, I find this readable tbh, if anyone else finds this a problem I can update. Thanks @eksperimental.

Comment (lexmag) [inline lib/elixir/lib/kernel/typespec.ex]: I like either no wrapping or `"`. :bowtie:

**Comment by josevalim** [comment]
:shipit:

File: lib/elixir/test/elixir/kernel/typespec_test.exs [hunk 2]
```diff
@@ -455,6 +455,27 @@ defmodule Kernel.TypespecTest do
            types(module)
   end
 
+  test "@type with module attributes" do
+    module = test_module do
+      @keyword Keyword
+      @type kw :: @keyword.t
+      @type kw_param(value) :: @keyword.t(value)
```
Comment (lexmag) [inline lib/elixir/test/elixir/kernel/typespec_test.exs]: I think `kw(value)` would be more consistent.
