### ISSUE TITLE
Cannot add compile-time only :extra_applications

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#12622]
### Elixir and Erlang/OTP versions

1.15.0-rc

### Operating system

macOS

### Current behavior

[x509](https://github.com/voltone/x509) uses :eep_dodger (part of :syntax_tools OTP app) module at compile-time. Since it's only used at compile-time ideally it would not be required to add it to :extra_applications which would then end up in people's releases.

This used to work on 1.14, albeit with a warning thanks to application tracker.

Maybe this is a use-case for `extra_applications: [epp_dodger: :optional]`?

References:
- https://github.com/voltone/x509/pull/53
- https://github.com/voltone/x509/pull/38#issuecomment-706705912
- [Module :epp_dodger is not available](https://elixirforum.com/t/module-epp-dodger-is-not-available/56185)

### Expected behavior

No compilation error.

**Comment by wojtekmach** [comment]
We can fix this by using Mix.ensure_application!/1. Thanks @josevalim!
