### ISSUE TITLE
Can no longer reference local record alias at compile time

### ISSUE THREAD

**Issue by chrismccord** [elixir-lang/elixir#1915]
``` elixir
# This worked on 0.10
defmodule Records do

  defmacro __using__(_) do
    quote do
      defrecord A, name: "chris"
      defrecord B, id: nil, nested: A.new
    end
  end

end

defmodule Example do
  use Records
end

# On 0.11.3 throws == Compilation error on file ./record_bug.ex ==
# ** (UndefinedFunctionError) undefined function: A.new/0

# Updating to use __MODULE__ prefix fixes issues on 0.11.3
defmodule Records do

  defmacro __using__(_) do
    quote do
      defrecord A, name: "chris"
      defrecord B, id: nil, nested: __MODULE__.A.new
    end
  end

end

defmodule Example do
  use Records
end
```

Is this a regression? If anyone knows where to start to fix this I would be happy to take a stab at it.
