### ISSUE TITLE
doctest with variable in result fails with "undefined variable" in 1.15, but worked in 1.14

### ISSUE THREAD

**Issue by breunigs** [elixir-lang/elixir#12729]
### Elixir and Erlang/OTP versions

broken:
```
Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.15.0 (compiled with Erlang/OTP 24)
```

working:
```
Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.14.5 (compiled with Erlang/OTP 24)
```

### Operating system

Debian

### Current behavior

1. `mix new debug && cd debug`
2. add this function to `lib/debug.ex`:
```elixir
  @doc """
  iex> num = 1
  iex> Debug.inc(num)
  num + 1
  """
  def inc(num), do: num + 1
```
3. `mix test`

It asserts fine with 1.14. 
1.15 reports:
```
Compiling 1 file (.ex)
Generated debug app
error: undefined variable "num"
  (for doctest at) lib/debug.ex:22: DebugTest."doctest Debug.inc/1 (2)"/1


== Compilation error in file test/debug_test.exs ==
** (CompileError) test/debug_test.exs: cannot compile module DebugTest (errors have been logged)
```

### Expected behavior

Code working in 1.14 continues to work in 1.15, or there's a hard deprecation notice in the changelog :)
