### ISSUE TITLE
Weird 'incompatible types' warning

### ISSUE THREAD

**Issue by mat-hek** [elixir-lang/elixir#11709]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0-dev (bdcf887) (compiled with Erlang/OTP 23)
```

Happens on Elixir 1.12.3 and 1.13.3 as well

* Operating system:  Mac OS 11.6

### Current behavior

Compiling this:

```elixir
defmodule A do
  def fun(state, key) do
    key0 = key
    state = %{state | key0 => true}
    key1 = key
    state = %{state | key1 => true}
    state
  end
end
```

gives this warning:

```
warning: incompatible types:

    map() !~ var2

in expression:

    # a.exs:6
    state = %{state | key1 => true}

where "state" was given the type map() in:

    # a.exs:6
    state = %{state | key1 => true}

Conflict found at
  a.exs:6: A.fun/2
```

### Expected behavior

No warning should be reported

**Comment by michallepicki** [comment]
Bug introduced by https://github.com/elixir-lang/elixir/pull/10320

I reduced it a bit more to:
```elixir
defmodule A do
  def fun(map0, key0) do
    map1 = %{map0 | key0 => true}
    key1 = key0
    map2 = %{map1 | key1 => true}
    map2
  end
end
```
which still warns, while this compiles cleanly:
```
defmodule A do
  def fun(map0, key0) do
    map1 = %{map0 | key0 => true}
    key1 = key0
    %{map1 | key1 => true}
  end
end
```

**Comment by michallepicki** [comment]
#10320 is mostly refactoring. One thing that it changed is that when validating a map update, the extra "open" map argument was [moved to the end of map args list](https://github.com/elixir-lang/elixir/pull/10320/files#diff-4b9f31154b7080efa898901fe2f698d4224edf10b8023206e07628193aeda01dR149), where it probably should be - before it [was prepended to the start of the map args list](https://github.com/elixir-lang/elixir/pull/10320/files#diff-4b9f31154b7080efa898901fe2f698d4224edf10b8023206e07628193aeda01dL397) for non-struct map updates. I'll look into the implementation of map updates validation introduced in https://github.com/elixir-lang/elixir/pull/10316 , maybe it can be improved.
