### ISSUE TITLE
Cldr fails to compile with Elixir 1.17.0-dev (64d6d3d)

### ISSUE THREAD

**Issue by moomerman** [elixir-lang/elixir#13575]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.17.0-dev (64d6d3d) (compiled with Erlang/OTP 26)

### Operating system

macOS Sonoma 14.5 (23F79)

### Current behavior

Our application fails to compile on 1.17-dev since 64d6d3d.

```
defmodule App.Cldr do
  @moduledoc """
  A config module for Cldr.
  """

  use Cldr,
    locales: ["en"],
    default_locale: "en",
    providers: [Cldr.List, Cldr.Number, Cldr.Unit, Cldr.DateTime]
end
```

```
~/wo/7s/phoenix spike-drawer-panel 7.6s | 1 » mix compile
Compiling 378 files (.ex)
Generating App.Cldr for 2 locales named [:en, :und] with a default locale named :en

== Compilation error in file lib/app/cldr.ex ==
** (ArgumentError) errors were found at the given arguments:

  * 3rd argument: not a list

    (stdlib 5.2.3) :lists.keyfind(2, 1, false)
    (elixir 1.17.0-dev) src/elixir_dispatch.erl:330: :elixir_dispatch.is_import/2
    (elixir 1.17.0-dev) src/elixir_dispatch.erl:301: :elixir_dispatch.find_import_by_name_arity/4
    (elixir 1.17.0-dev) src/elixir_dispatch.erl:164: :elixir_dispatch.expand_import/7
    (elixir 1.17.0-dev) src/elixir_dispatch.erl:127: :elixir_dispatch.dispatch_import/6
    (ex_cldr 2.38.1) /Users/richard/workspace/7sage/phoenix/lib/app/cldr.ex:1: Cldr.Backend.Compiler.__before_compile__/1
```

If this is a genuine bug with Cldr I will follow up with them.

### Expected behavior

Expected it to compile, compiles fine with Elixir 1.17-dev d11b41f65 and before.

**Comment by kipcole9** [comment]
I just tried your configuration on Elixir main which I installed with `asdf install elixir main` and it compiled to completion - with some expected warnings.

I have work to finish up the new `Calendar` callbacks so it's very possible there are going to be issues I need to resolve prior to its release of Elixir 1.17. I'm on Sonoma 14.2 on my MacBook Pro.

How did you install Elixir?  I'll try to reproduce on my system.

**Comment by josevalim** [comment]
I could reproduce it with this:

```
 Mix.install [:ex_cldr, :ex_cldr_numbers, :ex_cldr_units, :ex_cldr_lists, :ex_cldr_dates_times, :jason]
 
 defmodule App.Cldr do
  @moduledoc """
  A config module for Cldr.
  """

  use Cldr,
    locales: ["en"],
    default_locale: "en",
    providers: [Cldr.List, Cldr.Number, Cldr.Unit, Cldr.DateTime]
end
```

Don't worry @kipcole9, I am debugging it. :D

**Comment by josevalim** [comment]
The bug is in Cldr.DateTime, I can reproduce it with only it as a provider.

**Comment by kipcole9** [comment]
Arrghh, sorry Jose (and now my keyboard won't let me type your name properly).  Let me know what I need to do if you have any hints. (I can reproduce now too).

**Comment by josevalim** [comment]
It is an Elixir bug when there is a quote inside a quote :) Thank you @moomerman !
