### ISSUE TITLE
internal error in beam_dead on wrong record usage

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#8626]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.0-dev (786740a79) (compiled with Erlang/OTP 21)
* Operating system: macOS 

### Current behavior

As I've been moving code around I've accidentally ended up with a record definition _below_ the usage of generated some_record/2 function. Here's a repro:

This works:

```elixir
defmodule M do
  require Record
  Record.defrecord :point, [:x, :y]

  def xs(points) do
    Enum.map(points, &point(&1, :x))
  end
end
```

This crashes:

```elixir
defmodule M do
  def xs(points) do
    Enum.map(points, &point(&1, :x))
  end

  require Record
  Record.defrecord :point, [:x, :y]
end
```

```
% elixir a.ex
Function -xs/1-fun-0-/1 refers to undefined label 39
** (CompileError) a.ex: internal error in beam_dead;
crash reason: {case_clause,{'EXIT',{undefined_label,39}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
  in call from compile:fold_comp/4 (compile.erl, line 376)
  in call from compile:internal_comp/5 (compile.erl, line 360)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from elixir_erl_compiler:compile/4 (src/elixir_erl_compiler.erl, line 52)
  in call from elixir_erl:load_form/5 (src/elixir_erl.erl, line 444)
  in call from elixir_erl_compiler:'-spawn/2-fun-0-'/3 (src/elixir_erl_compiler.erl, line 12)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
    (elixir) lib/code.ex:767: Code.require_file/2

shell returned 1
```
### Expected behavior

Undefined function error.

**Comment by romul** [comment]
Looks like this one is kind of regression, b/c it worked on 1.7.4 as expected:
```
$ elixirc -v
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 20)

$ elixirc crash_record.ex

== Compilation error in file crash_record.ex ==
** (CompileError) crash_record.ex:3: undefined function point/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by fertapric** [comment]
I’m currently working on this one 🙂
