### ISSUE TITLE
ArgumentError when delegating a callback with a tuple as a parameter

### ISSUE THREAD

**Issue by sashaafm** [elixir-lang/elixir#5306]
### Precheck

I saw this [issue](https://github.com/elixir-lang/elixir/issues/4759) which seems to be a similar problem. I'm not entirely sure if my case is a bug or working as intended.

### Environment

* Elixir version (elixir -v): 1.3.2
* Erlang version (erl -v):  19
* Operating system:         Ubuntu 16.04 64-bit (Ubuntu Mate variant)

### Current behavior

When passing a tuple as an argument to the delegated function the following error appears:

```
== Compilation error on file lib/example.ex ==
** (ArgumentError) defdelegate/2 only accepts function parameters, got: {e, f}
    (elixir) lib/kernel/utils.ex:55: Kernel.Utils.add_arg/2
    (stdlib) lists.erl:1276: :lists.foldr/3
    (elixir) lib/kernel/utils.ex:25: Kernel.Utils.defdelegate/2
    lib/example.ex:4: anonymous fn/3 in :elixir_compiler_1.__MODULE__/1
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/example.ex:4: (module)
```

This was previously working on Elixir 1.1 and I believe also worked on 1.2 (I can't remember if I was working on this project while on 1.2).

I've built a sample project that reproduces the bug [here](https://github.com/sashaafm/delegate-bug). Just run `iex -S mix` and the error will pop.

### Expected behavior

The expected behavior in the previous Elixir version was to be able to delegate the function passing a tuple as an argument (and also having a tuple parameter defined in the signature). I've read the other issue about this, but I couldn't quite understand why having a tuple as a function parameter should throw an `ArgumentError`?

**Comment by josevalim** [comment]
It is an argument error during compilation. It means you are passing invalid arguments to defdelegate. You cannot pattern match at the same time you are delegating. If you need to pattern match, you should pattern match on the function you are delegating to, not on the one delegating.

**Comment by sashaafm** [comment]
Thank you José.
