### ISSUE TITLE
Invocation on require() does not work in 1.20

### ISSUE THREAD

**Issue by lud** [elixir-lang/elixir#15077]
### Elixir and Erlang/OTP versions

Erlang/OTP 28 [erts-16.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.20.0-rc.1 (3bb5f92) (compiled with Erlang/OTP 28)

### Operating system

Linux

### Current behavior

Hello,

I'm not sure if it is intended but the following code does not work anymore with Elixir 1.20:

```elixir
require(GenMCP.MCP.ModMap).require_all()
```

```
== Compilation error in file test/gen_mcp/mcp_test.exs ==
** (UndefinedFunctionError) function GenMCP.MCP.ModMap.require_all/0 is undefined or private. However, there is a macro with the same name and arity. Be sure to require GenMCP.MCP.ModMap if you intend to invoke this macro
    (gen_mcp 0.5.1) GenMCP.MCP.ModMap.require_all()
    test/gen_mcp/mcp_test.exs:7: (module)
    (elixir 1.20.0-rc.1) lib/kernel/parallel_compiler.ex:648: Kernel.ParallelCompiler.require_file/2
    (elixir 1.20.0-rc.1) lib/kernel/parallel_compiler.ex:531: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

This works as usual:

```elixir
require GenMCP.MCP.ModMap
GenMCP.MCP.ModMap.require_all()
```

Strange because `require` still returns the required module name.

### Expected behavior

Invocation on a required module name should work.

Well this is not a blocker in any way, but it may mean that some other constructs are made impossible now, so maybe this was not intended.

**Comment by josevalim** [comment]
It is a bug, thank you. I will investigate!

**Comment by josevalim** [comment]
@lud ok, so the issue is that `require Integer` returns an integer, but it no longer expands to an `Integer` at compile-time, since Elixir v1.20 now tracks unused requires. So we either need to remove the warning for unused requires, or we will need to introduce this potential breaking change. 😓 

Keep in mind this behaviour already existed for `import` and `alias`.

**Comment by lud** [comment]
Could the behaviour checks be made later during the compilation? Not sure if it could help but I have this use case:


```elixir
  defmacro do_stuff_with_behaviour(behaviour, some_fun) do

    check_behaviour(behaviour, __CALLER__)
    quote do
       # stuff that get

    end
  end

  defp check_behaviour(mod, _env) when is_atom(mod) do
    if {:module, mod} == Code.ensure_loaded(mod) and
         function_exported?(mod, :behaviour_info, 1) and
         match?([_ | _], mod.behaviour_info(:callbacks)) do
      :ok
    else
      raise ArgumentError,
            "#{inspect(mod)} is not a behaviour. `require #{inspect(mod)}` may solve the problem"
    end
  end

  defp check_behaviour({:__aliases__, _, _} = ast, env) do
    check_behaviour(Macro.expand_literals(ast, env), env)
  end
```

Problem with that is that the module that wants to use this macro most likely needs to `require SomeBehaviour` prior to calling the macro, but the compiler reports the require as unused now.

On that specific case I changed the macro so the check is done within the macro quoted block and not the macro-defining module, so I can now just inject the require myself. But I guess some other use cases are possible.


---

In the end I guess the breaking change is fine. The ability to make require+call  a one-liner is not very important, and is not idiomatic.

**Comment by josevalim** [comment]
I will add a note to the CHANGELOG then.
