### ISSUE TITLE
<%= %> tag causes compilation error on Elixir 1.10.0

### ISSUE THREAD

**Issue by pojiro** [elixir-lang/elixir#9755]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.0 (compiled with Erlang/OTP 22)
* Operating system: Linux

### Current behavior

<%= %>, this blank eex tag causes compilation error on Elixir 1.10.0 (compiled with Erlang/OTP 22).
It works on Elixir 1.9.1 (compiled with Erlang/OTP 22).

~~~
== Compilation error in file lib/test_web/views/layout_view.ex ==
** (ArgumentError) invalid value for option :linein quote, got: nil
    (elixir 1.10.0) src/elixir_quote.erl:55: :elixir_quote.validate_runtime/2
    lib/phoenix_html/engine.ex:98: Phoenix.HTML.Engine.to_safe/2
    lib/phoenix_html/engine.ex:62: Phoenix.HTML.Engine.handle_expr/3
    (eex 1.10.0) lib/eex/compiler.ex:46: EEx.Compiler.generate_buffer/4
    (phoenix 1.4.12) lib/phoenix/template.ex:355: Phoenix.Template.compile/3
    (phoenix 1.4.12) lib/phoenix/template.ex:166: anonymous fn/4 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir 1.10.0) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix 1.4.12) expanding macro: Phoenix.Template.__before_compile__/1
    lib/test_web/views/layout_view.ex:1: TestWeb.LayoutView (module)
    (elixir 1.10.0) lib/kernel/parallel_compiler.ex:233: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
~~~

### Expected behavior

It depends on Elixir specification

**Comment by ckruse** [comment]
This happens for me, too, but not only on empty eex tags (Elixir 1.10.0 (compiled with Erlang/OTP 22)). But only for two of my three Elixir projects.

**Comment by ckruse** [comment]
Ok, found my problematic code: for me it is `{:safe, expression}`, e.g. `{:safe, ""}`

**Comment by josevalim** [comment]
I have released Phoenix.HTML v2.13.4 with a fix. LiveView also has the same issue, so you will need master in there for now (v0.6 upcoming).

**Comment by pojiro** [comment]
@josevalim 
I tried with Phoenix.HTML v2.13.4 and it works on Elixir 1.10.0. Thanks!

**Comment by ckruse** [comment]
Confirmed, works with oupdated Phoenix.HTML 👍

**Comment by josevalim** [comment]
I have reverted the check on the v1.10 branch, which means v1.10.1 will also work with old Phoenix.HTML versions. However, v1.11 will re-introduce the check, which is an important one, but hopefully by then most people have updated their deps. :)

**Comment by josevalim** [comment]
I have reverted the verification on v1.10.1 but it will be added back on v1.11.0, so be sure to update your deps. Thanks everyone!
