### ISSUE TITLE
Recompile project when OTP version changes

### ISSUE THREAD

**Issue by sphinxc0re** [elixir-lang/elixir#6066]
### Environment

* Elixir & Erlang versions: Elixir 1.4.2 OTP 19.3
* Operating system: macOS

### Current behavior

Phoenix app (or any other app) doesn't compile with Erlang OTP 19.3 although it did compile with 18.3

The following log output is produced:
```
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Compiling 33 files (.ex)

== Compilation error on file lib/stationeer/web/router.ex ==
** (CompileError) lib/stationeer/web/router.ex: internal error in v3_core;
crash reason: {case_clause,
    {'EXIT',
        {badarg,
            [{erl_anno,anno_info,[-1],[{file,"erl_anno.erl"},{line,360}]},
             {v3_core,record_anno,2,[{file,"v3_core.erl"},{line,2410}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,539}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,528}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,'-safe_list/2-anonymous-0-',2,
                 [{file,"v3_core.erl"},{line,1608}]},
             {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,538}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,'-safe_list/2-anonymous-0-',2,
                 [{file,"v3_core.erl"},{line,1608}]},
             {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,538}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,528}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,'-safe_list/2-anonymous-0-',2,
                 [{file,"v3_core.erl"},{line,1608}]},
             {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,652}]},
             {v3_core,exprs,2,[{file,"v3_core.erl"},{line,512}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/2 (compile.erl, line 544)
  in call from compile:'-internal_comp/4-anonymous-1-'/2 (compile.erl, line 329)
  in call from compile:fold_comp/3 (compile.erl, line 355)
  in call from compile:internal_comp/4 (compile.erl, line 339)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from compile:'-do_compile/2-anonymous-1-'/1 (compile.erl, line 190)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (phoenix) expanding macro: Phoenix.Router.__before_compile__/1
    lib/stationeer/web/router.ex:1: Stationeer.Web.Router (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

### Expected behavior

Phoenix app (or any other app) compiles under 19.3 😉

**Comment by josevalim** [comment]
What is your Phoenix and Phoenix.HTML versions? I believe this particular bug has been fixed on Phoenix 1.2.1.

**Comment by sphinxc0re** [comment]
```elixir
{:phoenix, "~> 1.3.0-rc", override: true},
{:phoenix_html, "~> 2.6"},
```

**Comment by josevalim** [comment]
@sphinxc0re thank you! Can you please try Elixir master and let us know if it is fixed there? I am thinking it may be the same as #6015 .

**Comment by josevalim** [comment]
@sphinxc0re actually, I don't think #6015 will be the cause here. Hrm... can you please provide an app that reproduces the error so we can take a further look?

**Comment by sphinxc0re** [comment]
Sure: https://github.com/sphinxc0re/dummy-phx

**Comment by sphinxc0re** [comment]
I'm currently at the ElixirConfEU if you want to meet up and solve the problem 😉

**Comment by josevalim** [comment]
Yes please! I am on room 9 close to the Elixir cards stand!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by sphinxc0re** [comment]
Hmm... I seem to have missed you. You are in room `mr. 9` right?

**Comment by josevalim** [comment]
Yup, MR09, where the stands are. Sitting here right now.

**Comment by josevalim** [comment]
So the issue is that the code was compiled with Erlang 18 and then moved to Erlang 19. We should probably store the Erlang version on Mix too and recompile when it changes.

**Comment by sphinxc0re** [comment]
👏 thank you @josevalim
