### ISSUE TITLE
:application.get_application/1 always returns :undefined during compilation

### ISSUE THREAD

**Issue by Awlexus** [elixir-lang/elixir#8699]
Since I updated to elixir 1.8 I'm getting `:undefined` as a result for `:application.get_application/1` when I call it inside a macro/during compile time. This happens when the example code is run inside iex or during compiling a mix project

### Environment
Elixir version (Default pacman package):
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.0 (compiled with Erlang/OTP 21)

Operating system: 
Arch Linux
Kernel: x86_64 Linux 4.20.3-arch1-1-ARCH

### Current behavior

```elixir
defmodule Test do
  defmacro __using__(_opts) do
     {:ok, application} = :application.get_application(__CALLER__.module) # Returns :undefined
  end
end

defmodule Test2 do
  use Test
end
```

This causes the following error:
```
== Compilation error in file lib/test.ex ==
** (MatchError) no match of right hand side value: :undefined
    expanding macro: Test.__using__/1
    lib/test.ex:8: Test2 (module)
    (elixir) expanding macro: Kernel.use/1
    lib/test.ex:8: Test2 (module)
```
### Expected behavior

Returns an ok-tuple with the application of the module

**Comment by josevalim** [comment]
Which value did it return in Elixir versions? I don't see how this could have worked before because when you are compiling the module, the application has not yet been defined, so it can't have any processes belonging to it and the modules do not yet know to which application they belongs to.

**Comment by Awlexus** [comment]
I cannot say for sure. I always used the returned application to get a configuration value with `Application.get_env/3`. So there's a good chance it never returned the actual application. But at the very least I can confirm that it matched `{:ok, application}`

After work I can set up a virtual environment with elixir 1.7 and inspect the exact output.

**Comment by OvermindDL1** [comment]
> Supposedly vitamin D helps with depression. I was in a slump for a bit (student loans and thesis). Started to exercise again and drinking a lot of milk so I’m happy and content now. Could be placebo but I’ll take it.

For note, you should look into https://github.com/asdf-vm/asdf as you can choose versions of elixir and erlang even on a directory-by-directory basis.  :-)

I just tested your above code:
```zsh
~/elixir/tmp/1.7.4/tester> cat lib/tester.ex
defmodule Test do
    defmacro __using__(_opts) do
           {:ok, application} = :application.get_application(__CALLER__.module) # Returns :undefined
             end
end

defmodule Test2 do
    use Test
end
~/elixir/tmp/1.7.4/tester> elixir -v
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
~/elixir/tmp/1.7.4/tester> mix compile
Compiling 1 file (.ex)
warning: variable "application" is unused
  lib/tester.ex:3


== Compilation error in file lib/tester.ex ==
** (MatchError) no match of right hand side value: :undefined
    expanding macro: Test.__using__/1
    lib/tester.ex:8: Test2 (module)
    (elixir) expanding macro: Kernel.use/1
    lib/tester.ex:8: Test2 (module)
~/elixir/tmp/1.7.4/tester> asdf local elixir 1.6.6                                                                                1 ↵
~/elixir/tmp/1.7.4/tester> elixir -v              
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Elixir 1.6.6 (compiled with OTP 19)
~/elixir/tmp/1.7.4/tester> mix compile
Compiling 1 file (.ex)
warning: variable "application" is unused
  lib/tester.ex:3


== Compilation error in file lib/tester.ex ==
** (MatchError) no match of right hand side value: :undefined
    expanding macro: Test.__using__/1
    lib/tester.ex:8: Test2 (module)
    (elixir) expanding macro: Kernel.use/1
    lib/tester.ex:8: Test2 (module)
```
Thus it didn't work in 1.7.4 nor 1.6.6?

**Comment by Awlexus** [comment]
I'm sorry, I made a very big mistake. Apparently I just recently changed the lefhand side from `application` to `{:, application}`
