### ISSUE TITLE
Compilation error for :jsv dep and elixir 1.20-rc.4

### ISSUE THREAD

**Issue by moomerman** [elixir-lang/elixir#15358]
### Elixir and Erlang/OTP versions

Yesterday we bumped `req_llm` from 0.18.3 → 0.19.0 and its transitive dependency `{:jsv, "~> 0.11"}` fails to compile on elixir 1.20-rc.4 (and main@7e49585d2).  

Switching back to elixir 1.19 works.

Erlang/OTP 28 [erts-16.3.1]

### Operating system

macOS

### Current behavior

Here's the compilation error output:

`MIX_OS_DEPS_COMPILE_PARTITION_COUNT=1 mix compile`

```
===> Analyzing applications...
===> Compiling hpack
==> jsv
Compiling 72 files (.ex)

== Compilation error in file lib/jsv/schema.ex ==
** (RuntimeError) found error while checking types for JSV.Schema.xcast/1:

** (MatchError) no match of right hand side value:

    %{
      vars: %{
        0 => %{
          name: :caster,
          type: :term,
          context: nil,
          deps: %{},
          paths: [],
          off_traces: []
        }
      },
      warnings: [],
      failed: false,
      local_sigs: %{
        {:__struct__, 0} => {:def,
         {:infer, nil,
          [
            {[],
             %{
               map: {:closed,
                [
                  "$anchor": %{atom: {:union, %{nil: []}}},
                  "$comment": %{atom: {:union, %{nil: []}}},
                  "$defs": %{atom: {:union, %{nil: []}}},
                  "$dynamicAnchor": %{atom: {:union, %{nil: []}}},
                  "$dynamicRef": %{atom: {:union, %{nil: []}}},
                  "$id": %{atom: {:union, %{nil: []}}},
                  "$ref": %{atom: {:union, %{nil: []}}},
                  "$schema": %{atom: {:union, %{nil: []}}},
                  __struct__: %{atom: {:union, %{JSV.Schema => []}}},
                  additionalItems: %{atom: {:union, %{nil: []}}},
                  additionalProperties: %{atom: {:union, %{nil: []}}},
                  allOf: %{atom: {:union, %{nil: []}}},
                  anyOf: %{atom: {:union, %{nil: []}}},
                  contains: %{atom: {:union, %{nil: []}}},
                  contentEncoding: %{atom: {:union, %{nil: []}}},
                  ...
                ]}
             }}
          ]}, ...},
        ...
      },
      ...
    }

The exception happened while checking this code:

def (((xcast(caster) when :erlang.is_binary(caster)) when :erlang.is_atom(caster))
     when :erlang.is_binary(:erlang.hd(caster)))
    when :erlang.is_atom(:erlang.hd(caster)) do
  xcast(%{}, caster)
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

    (elixir 1.20.0-rc.4) lib/module/types/of.ex:98: Module.Types.Of.refine_body_var/5
    (elixir 1.20.0-rc.4) lib/module/types/helpers.ex:562: Module.Types.Helpers.zip_map_reduce/5
    (elixir 1.20.0-rc.4) lib/module/types/apply.ex:368: Module.Types.Apply.remote/8
    (elixir 1.20.0-rc.4) lib/module/types/pattern.ex:1045: anonymous fn/4 in Module.Types.Pattern.of_guards/3
    (elixir 1.20.0-rc.4) lib/enum.ex:1851: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.20.0-rc.4) lib/enum.ex:1851: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.20.0-rc.4) lib/module/types/pattern.ex:1044: Module.Types.Pattern.of_guards/3
    (elixir 1.20.0-rc.4) lib/module/types/pattern.ex:1030: Module.Types.Pattern.of_guards/4
```

### Expected behavior

jsv should compile

**Comment by josevalim** [comment]
Thank you, I can reproduce it with:

```
defmodule Foo do
  def xcast(caster)
      when is_binary(hd(caster))
      when is_atom(hd(caster)) do
    IO.inspect(caster)
  end
end
```

It is most likely the user of `hd(caster)` across `when` clauses.
