### ISSUE TITLE
defoverridable compilation error 1.7.0-dev regression

### ISSUE THREAD

**Issue by thetamind** [elixir-lang/elixir#7823]
### Environment

* Elixir & Erlang/OTP versions: Elixir 1.7.0-dev (693e051c0); Erlang/OTP 20 [erts-9.3.2]  
* Operating system: macOS 10.11.6

### Current behavior

```
$ mix archive.install hex raxx_kit 0.5.2
$ mix raxx.kit watercooler
$ cd watercooler
$ mix deps.get
$ mix compile

== Compilation error in file lib/watercooler/www.ex ==
** (ArgumentError) cannot make function handle_request/2 overridable because it was not defined
    (elixir) lib/module.ex:938: anonymous fn/2 in Module.make_overridable/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    lib/watercooler/www.ex:1: Raxx.Logger.__before_compile__/1
```

### Expected behavior

Compiles successfully as it does on Elixir 1.6.5. 

### Regression

`git bisect` finds 8c85557346dea1166d703bfbf109ccb0f1196517 - (Share Bag and Set tables across a module functionality) as the first bad commit. There were no test file modified so I'm not expecting a behavoiur change here.

#### 1. Raxx test suite

`Raxx` includes a simple example in [`test/raxx/logger_test.exs`][raxx-test] run with `mix test`. Both `use Raxx.Logger` or `use Raxx.RequestID` fail to compile.

```elixir
  defmodule DefaultServer do
    use Raxx.Server
    use Raxx.Logger
  end
```

```
$ mix test
== Compilation error in file test/raxx/logger_test.exs ==
** (ArgumentError) cannot make function handle_data/2 overridable because it was not defined
    (elixir) lib/module.ex:938: anonymous fn/2 in Module.make_overridable/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (raxx) test/raxx/logger_test.exs:5: Raxx.Logger.__before_compile__/1
```

[raxx-test]: https://github.com/CrowdHailer/raxx/blob/a1c4b2a5f4a7594e8e73102209c09690cd3a032d/test/raxx/logger_test.exs#L5-L8

#### 2. Simpler example without `@before_compile` as in Raxx above

https://gist.github.com/thetamind/817be56b3cb17d0ad928eba5dcb12823

**Comment by josevalim** [comment]
Excellent. Thanks for giving master a try!
