### ISSUE TITLE
Possible breaking change in |>

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12070]
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0-rc.0 (e81e9f7) (compiled with Erlang/OTP 24)

### Operating system

macos

### Current behavior

Reproduction:
1. clone git@github.com:xerions/phoenix_swagger.git
2. mix install
3. mix test

Result:
```
== Compilation error in file test/path_test.exs ==
** (ArgumentError) cannot pipe %PhoenixSwagger.Path.PathObject{} into get("/api/v1/users/{id}")
|> summary("Get a user")
|> description("Get a user by ID")
|> parameter("id", :path, :string, "User ID", required: true, example: "123")
|> response(200, "OK", :User), the :|> operator can only take two arguments
    (elixir 1.14.0-rc.0) lib/macro.ex:323: Macro.pipe/3
    (elixir 1.14.0-rc.0) expanding macro: Kernel.|>/2
    test/path_test.exs:7: PhoenixSwagger.PathTest.swagger_path_show/1
    (elixir 1.14.0-rc.0) expanding macro: Kernel.|>/2
    test/path_test.exs:7: PhoenixSwagger.PathTest.swagger_path_show/1
    (elixir 1.14.0-rc.0) expanding macro: Kernel.|>/2
    test/path_test.exs:7: PhoenixSwagger.PathTest.swagger_path_show/1
    (elixir 1.14.0-rc.0) expanding macro: Kernel.|>/2
    test/path_test.exs:7: PhoenixSwagger.PathTest.swagger_path_show/1
    (elixir 1.14.0-rc.0) expanding macro: Kernel.|>/2
    test/path_test.exs:7: PhoenixSwagger.PathTest.swagger_path_show/1
    (elixir 1.14.0-rc.0) expanding macro: Kernel.|>/2
    test/path_test.exs:7: PhoenixSwagger.PathTest.swagger_path_show/1
```

### Expected behavior

Project should continue to work on 1.14. There is no mention in release notes about any changes related to `|>`.
