### ISSUE TITLE
1.20.0-rc.1 compilation error

### ISSUE THREAD

**Issue by preciz** [elixir-lang/elixir#15074]
### Elixir and Erlang/OTP versions

I was curious if our app compiles with 1.20.0-rc.1 and it doesn't:

```text
== Compilation error in file lib/octo/worker/monitor_document.ex ==
** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.all_matching_keywords/2:

** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.compute_keyword_results/3:

** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.compute_matching_page_numbers/3:

** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.apply_negative_context/5:

** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.do_compute_matching_page_numbers/3:

** (MatchError) no match of right hand side value:

    %{
      vars: %{
        0 => %{
          name: :table_uid,
          type: %{dynamic: :term},
          context: nil,
          deps: %{},
          paths: [],
          off_traces: [
            {{:table_uid, [version: 0, line: 196, column: 40], nil},
             "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
             %{dynamic: :term}}
          ]
        },
        1 => %{
          name: :term,
          type: %{dynamic: %{bitmap: 1}},
          context: nil,
          deps: %{},
          paths: [],
          off_traces: [
            {{:dynamic_query_type, [line: 198, column: 26],
              [{:term, [version: 1, line: 198, column: 45], nil}]},
             "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
             %{dynamic: %{bitmap: 1}}},
            {{:term, [version: 1, line: 196, column: 51], nil},
             "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
             %{dynamic: :term}}
          ]
        },
        2 => %{
          name: :document_text,
          type: %{dynamic: :term},
          context: nil,
          deps: %{},
          paths: [],
          off_traces: [
            {{:document_text, [version: 2, line: 196, column: 57], nil},
             "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
             %{dynamic: :term}}
          ]
        },
        3 => %{
          name: :cache,
          type: %{atom: {:union, %{Octo.Cache => []}}},
          context: Nebulex.Caching.Decorators,
          deps: %{},
          paths: [],
          off_traces: [
            {{:=, [line: 1],
              [{:cache, [version: 3, line: 1], Nebulex.Caching.Decorators}, ...]},
             ...}
          ]
        },
        ...
      },
      ...
    }

The exception happened while checking this code:

def do_compute_matching_page_numbers(table_uid, term, document_text) do
  cache = Octo.Cache
  opts = []

  match = fn
    {:error, _} -> false
    :error -> false
    nil -> false
    _ -> true
  end

  on_error = :raise

  Nebulex.Caching.Decorators.eval_cacheable(
    cache,
    {:do_compute_matching_page_numbers, table_uid, term},
    nil,
    opts,
    on_error,
    match,
    fn ->
      table_name = Octo.Worker.MonitorDocument.DocumentPage.table_name(table_uid)
      dynamic_query_type = dynamic_query_type(term)

      case :erlang.==(dynamic_query_type, :exact) do
        false ->
          repo().all(
            (
              query =
                Ecto.Query.Builder.Filter.filter!(
                  :where,
                  :and,
                  Ecto.Query.Builder.From.apply(
                    {table_name, Octo.Worker.MonitorDocument.DocumentPage},
                    1,
                    nil,
                    nil,
                    []
                  ),
                  dynamic_term_query(dynamic_query_type, term),
                  0,
                  "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
                  217
                )

              Ecto.Query.Builder.Select.apply(query, %Ecto.Query.SelectExpr{
                fields: nil,
                expr: {{:., [], [{:&, [], [0]}, :number]}, [], []},
                params: [],
                file: "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
                line: 217,
                take: %{},
                subqueries: [],
                aliases: %{}
              })
            )
          )

        true ->
          regex =
            Regex.compile!(
              String.replace(
                String.replace_trailing(
                  String.replace_leading(
                    Octo.Helpers.String.trim_quotes!(String.downcase(term)),
                    " ",
                    "\\b"
                  ),
                  " ",
                  "\\b"
                ),
                " ",
                "\\W+"
              )
            )

          Enum.to_list(
            Stream.map(
              Stream.filter(
                document_text.pages,
                fn %{text: text, ocr_text: ocr_text} ->
                  case Kernel.=~(String.downcase(text), regex) do
                    false -> Kernel.=~(String.downcase(ocr_text), regex)
                    true -> true
                    other -> :erlang.error({:badbool, :or, other})
                  end
                end
              ),
              fn capture -> capture.number end
            )
          )
      end
    end
  )
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

def apply_negative_context(
      matching_page_numbers,
      table_uid,
      term,
      [_ | _] = context_terms,
      document_text
    ) do
  page_numbers_of_context_terms =
    Enum.into(context_terms, %{}, fn context_term ->
      {context_term, do_compute_matching_page_numbers(table_uid, context_term, document_text)}
    end)

  any_context_term_matches? = fn page_number ->
    Enum.any?(
      context_terms,
      fn context_term ->
        context_term_page_numbers = :maps.get(context_term, page_numbers_of_context_terms)

        context_term_matches?(
          table_uid,
          page_number,
          term,
          context_term,
          context_term_page_numbers
        )
      end
    )
  end

  Enum.reject(
    matching_page_numbers,
    fn {page_number, _context_terms} -> any_context_term_matches?.(page_number) end
  )
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

def compute_matching_page_numbers(
      table_uid,
      %Octo.Crawl.Keyword{main: main, context: context, negative_context: negative_context},
      document_text
    )
    when :erlang.is_binary(table_uid) do
  apply_negative_context(
    apply_context(
      do_compute_matching_page_numbers(table_uid, main, document_text),
      table_uid,
      main,
      context,
      document_text
    ),
    table_uid,
    main,
    negative_context,
    document_text
  )
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

def compute_keyword_results(keywords, table_uid, document_text) do
  Enum.flat_map(
    keywords,
    fn %Octo.Crawl.Keyword{} = keyword ->
      Enum.map(
        compute_matching_page_numbers(table_uid, keyword, document_text),
        fn {page_number, context_terms} ->
          %{
            keyword: keyword,
            keyword_id: keyword.id,
            page_number: page_number,
            context_terms: context_terms
          }
        end
      )
    end
  )
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

def all_matching_keywords(%Octo.Object.Document{sha256: sha256}, keywords) do
  document_text = Octo.Object.DocumentText.get!(sha256)

  with_table!(document_text, fn table_uid ->
    compute_keyword_results(keywords, table_uid, document_text)
  end)
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

    (elixir 1.20.0-rc.1) lib/module/types/of.ex:95: Module.Types.Of.refine_body_var/5
    (elixir 1.20.0-rc.1) lib/module/types/of.ex:206: anonymous fn/6 in Module.Types.Of.reduce_conditional_vars/4
    (elixir 1.20.0-rc.1) lib/enum.ex:2617: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.20.0-rc.1) lib/module/types/of.ex:189: Module.Types.Of.with_conditional_vars/6
    (elixir 1.20.0-rc.1) lib/module/types/expr.ex:720: anonymous fn/10 in Module.Types.Expr.of_clauses_fun/9
    (elixir 1.20.0-rc.1) lib/enum.ex:2617: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.20.0-rc.1) lib/module/types/expr.ex:315: Module.Types.Expr.of_expr/5
    (elixir 1.20.0-rc.1) lib/module/types/expr.ex:720: anonymous fn/10 in Module.Types.Expr.of_clauses_fun/9
```

### Operating system

CachyOS Linux

### Current behavior

It doesn't compile

### Expected behavior

It compiles

**Comment by josevalim** [comment]
@preciz can you please try the main branch just in case we have fixed it already?

**Comment by preciz** [comment]
Ok I made sure that I compile it with that:
```
❯ mise ls elixir
Tool    Version        Source                      Requested
elixir  1.19.4-otp-28
elixir  1.19.5-otp-28  ~/.config/mise/config.toml  latest

~/workspace
❯ rm -rf octo/_build

~/workspace
❯ elixir -v
Erlang/OTP 28 [erts-16.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.20.0-rc.1 (e87b935) (compiled with Erlang/OTP 28)

~/workspace
❯ which elixir
/home/p/workspace/elixir/bin/elixir

~/workspace
❯ cd octo && source .dev.env && mix compile
```

The error:

```
== Compilation error in file lib/octo/worker/monitor_document.ex ==
** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.all_matching_keywords/2:

** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.compute_keyword_results/3:

** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.compute_matching_page_numbers/3:

** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.apply_negative_context/5:

** (RuntimeError) found error while checking types for Octo.Worker.MonitorDocument.do_compute_matching_page_numbers/3:

** (MatchError) no match of right hand side value:

    %{
      vars: %{
        0 => %{
          name: :table_uid,
          type: %{dynamic: :term},
          context: nil,
          deps: %{},
          paths: [],
          off_traces: [
            {{:table_uid, [version: 0, line: 196, column: 40], nil},
             "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
             %{dynamic: :term}}
          ]
        },
        1 => %{
          name: :term,
          type: %{dynamic: %{bitmap: 1}},
          context: nil,
          deps: %{},
          paths: [],
          off_traces: [
            {{:dynamic_query_type, [line: 198, column: 26],
              [{:term, [version: 1, line: 198, column: 45], nil}]},
             "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
             %{dynamic: %{bitmap: 1}}},
            {{:term, [version: 1, line: 196, column: 51], nil},
             "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
             %{dynamic: :term}}
          ]
        },
        2 => %{
          name: :document_text,
          type: %{dynamic: :term},
          context: nil,
          deps: %{},
          paths: [],
          off_traces: [
            {{:document_text, [version: 2, line: 196, column: 57], nil},
             "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
             %{dynamic: :term}}
          ]
        },
        3 => %{
          name: :cache,
          type: %{atom: {:union, %{Octo.Cache => []}}},
          context: Nebulex.Caching.Decorators,
          deps: %{},
          paths: [],
          off_traces: [
            {{:=, [line: 1],
              [{:cache, [version: 3, line: 1], Nebulex.Caching.Decorators}, ...]},
             ...}
          ]
        },
        ...
      },
      ...
    }

The exception happened while checking this code:

def do_compute_matching_page_numbers(table_uid, term, document_text) do
  cache = Octo.Cache
  opts = []

  match = fn
    {:error, _} -> false
    :error -> false
    nil -> false
    _ -> true
  end

  on_error = :raise

  Nebulex.Caching.Decorators.eval_cacheable(
    cache,
    {:do_compute_matching_page_numbers, table_uid, term},
    nil,
    opts,
    on_error,
    match,
    fn ->
      table_name = Octo.Worker.MonitorDocument.DocumentPage.table_name(table_uid)
      dynamic_query_type = dynamic_query_type(term)

      case :erlang.==(dynamic_query_type, :exact) do
        false ->
          repo().all(
            (
              query =
                Ecto.Query.Builder.Filter.filter!(
                  :where,
                  :and,
                  Ecto.Query.Builder.From.apply(
                    {table_name, Octo.Worker.MonitorDocument.DocumentPage},
                    1,
                    nil,
                    nil,
                    []
                  ),
                  dynamic_term_query(dynamic_query_type, term),
                  0,
                  "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
                  217
                )

              Ecto.Query.Builder.Select.apply(query, %Ecto.Query.SelectExpr{
                fields: nil,
                expr: {{:., [], [{:&, [], [0]}, :number]}, [], []},
                params: [],
                file: "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
                line: 217,
                take: %{},
                subqueries: [],
                aliases: %{}
              })
            )
          )

        true ->
          regex =
            Regex.compile!(
              String.replace(
                String.replace_trailing(
                  String.replace_leading(
                    Octo.Helpers.String.trim_quotes!(String.downcase(term)),
                    " ",
                    "\\b"
                  ),
                  " ",
                  "\\b"
                ),
                " ",
                "\\W+"
              )
            )

          Enum.to_list(
            Stream.map(
              Stream.filter(
                document_text.pages,
                fn %{text: text, ocr_text: ocr_text} ->
                  case Kernel.=~(String.downcase(text), regex) do
                    false -> Kernel.=~(String.downcase(ocr_text), regex)
                    true -> true
                    other -> :erlang.error({:badbool, :or, other})
                  end
                end
              ),
              fn capture -> capture.number end
            )
          )
      end
    end
  )
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

def apply_negative_context(
      matching_page_numbers,
      table_uid,
      term,
      [_ | _] = context_terms,
      document_text
    ) do
  page_numbers_of_context_terms =
    Enum.into(context_terms, %{}, fn context_term ->
      {context_term, do_compute_matching_page_numbers(table_uid, context_term, document_text)}
    end)

  any_context_term_matches? = fn page_number ->
    Enum.any?(
      context_terms,
      fn context_term ->
        context_term_page_numbers = :maps.get(context_term, page_numbers_of_context_terms)

        context_term_matches?(
          table_uid,
          page_number,
          term,
          context_term,
          context_term_page_numbers
        )
      end
    )
  end

  Enum.reject(
    matching_page_numbers,
    fn {page_number, _context_terms} -> any_context_term_matches?.(page_number) end
  )
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

def compute_matching_page_numbers(
      table_uid,
      %Octo.Crawl.Keyword{main: main, context: context, negative_context: negative_context},
      document_text
    )
    when :erlang.is_binary(table_uid) do
  apply_negative_context(
    apply_context(
      do_compute_matching_page_numbers(table_uid, main, document_text),
      table_uid,
      main,
      context,
      document_text
    ),
    table_uid,
    main,
    negative_context,
    document_text
  )
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

def compute_keyword_results(keywords, table_uid, document_text) do
  Enum.flat_map(
    keywords,
    fn %Octo.Crawl.Keyword{} = keyword ->
      Enum.map(
        compute_matching_page_numbers(table_uid, keyword, document_text),
        fn {page_number, context_terms} ->
          %{
            keyword: keyword,
            keyword_id: keyword.id,
            page_number: page_number,
            context_terms: context_terms
          }
        end
      )
    end
  )
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

The exception happened while checking this code:

def all_matching_keywords(%Octo.Object.Document{sha256: sha256}, keywords) do
  document_text = Octo.Object.DocumentText.get!(sha256)

  with_table!(document_text, fn table_uid ->
    compute_keyword_results(keywords, table_uid, document_text)
  end)
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

    (elixir 1.20.0-rc.1) lib/module/types/of.ex:95: Module.Types.Of.refine_body_var/5
    (elixir 1.20.0-rc.1) lib/module/types/of.ex:210: anonymous fn/6 in Module.Types.Of.reduce_conditional_vars/4
    (elixir 1.20.0-rc.1) lib/enum.ex:2617: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.20.0-rc.1) lib/module/types/of.ex:193: Module.Types.Of.with_conditional_vars/6
    (elixir 1.20.0-rc.1) lib/module/types/expr.ex:720: anonymous fn/10 in Module.Types.Expr.of_clauses_fun/9
    (elixir 1.20.0-rc.1) lib/enum.ex:2617: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.20.0-rc.1) lib/module/types/expr.ex:315: Module.Types.Expr.of_expr/5
    (elixir 1.20.0-rc.1) lib/module/types/expr.ex:720: anonymous fn/10 in Module.Types.Expr.of_clauses_fun/9

  "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
  %{dynamic: %{bitmap: 1}}},
  {{:term, [version: 1, line: 196, column: 51], nil},
  "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
  %{dynamic: :term}}
  ]
  },
  2 => %{
  name: :document_text,
  type: %{dynamic: :term},
  context: nil,
  deps: %{},
  paths: [],
  off_traces: [
  {{:document_text, [version: 2, line: 196, column: 57], nil},
  "/home/p/workspace/octo/lib/octo/worker/monitor_document.ex",
  %{dynamic: :term}}
  ]
  },
  3 => %{
  name: :cache,
  type: %{atom: {:union, %{Octo.Cache => []}}},
  context: Nebulex.Caching.Decorators,
  deps: %{},
  paths: [],
  off_traces: [
  {{:=, [line: 1],
  [{:cache, [version: 3, line: 1], Nebulex.Caching.Decorators}, ...]},
  ...}
  ]
```

**Comment by preciz** [comment]
@josevalim AI made a small private repo that replicates the error. I invited you as a collaborator.

**Comment by josevalim** [comment]
Thank you, here is a minimal repro:

```
defmodule Foo do
  def repo() do
    mod =
      if :rand.uniform() > 0.5 do
        Integer
      else
        Float
      end

    mod.to_string(
      (
        query = Integer.to_string(123)
        String.to_integer(query)
      )
    )
  end
end
```
