### ISSUE TITLE
Recursive binary pattern matching + binary `for` comprehension => Internal consistency check failed

### ISSUE THREAD

**Issue by jechol** [elixir-lang/elixir#10309]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Operating system: macOS

### Current behavior

When `bin` is pattern matched as binary twice and then used in binary `for` comprehension,
`Internal consistency check failed`

```elixir
def encode_bin(<<bin::binary>> = bin) do
  for <<chunk::binary-size(5) <- bin>> do
    chunk
  end
end
```

```
== Compilation error in file lib/recursive_pattern.ex ==
** (CompileError) Elixir.RecursivePattern: function encode_bin/1+13:
  Internal consistency check failed - please report this bug.
  Instruction: {call_only,1,{f,17}}
  Error:       {bad_arg_type,{x,0},{t_bs_context,1,0,0},{t_bs_context,8,0,0}}:

    (stdlib 3.13) lists.erl:1338: :lists.foreach/2
    (elixir 1.10.4) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
```

I have uploaded simple project to reproduce this easily. 
https://github.com/jechol/recursive_pattern

### Expected behavior

Same code is working well with Elixir 1.10.4 + OTP 22.

**Comment by josevalim** [comment]
@jechol thanks for the great report! Reported upstream here: https://bugs.erlang.org/browse/ERL-1340

**Comment by jhogberg** [comment]
We'll release a fix in OTP 23.1 next week. Thanks again for your report!
