### PR TITLE
User defined types with the name `record` fail to compile in 1.8.0-rc.0

### LINKED ISSUE #8568: 1.8.0-rc.0: unable to compile with supplied Makefile
Hi all,

Having a quick look at 1.8 rc 0 and could not compile it with the supplied Makefile.

### Environment

Erlang 21.2-1 (esl-erlang from Erlang Solns ppa)
 
Ubuntu 18.04 with latest maintenance

### Current behaviour

Standard elixir build:

`make clean test`

and I eventually see some warnings (which seem to be in 1.7.4 also):

> ==> elixir (compile)
> warning: module Exception is not a behaviour (in module IO.StreamError)
  lib/io/stream.ex:1

> warning: got "@impl true" for function message/1 but no behaviour specifies such callback. There are no known callbacks, please specify the proper @behaviour and make sure it defines callbacks
  lib/io/stream.ex:2

> warning: got "@impl true" for function exception/1 but no behaviour specifies such callback. There are no known callbacks, please specify the proper @behaviour and make sure it defines callbacks
  lib/io/stream.ex:2

> warning: got "@impl true" for function exception/1 but no behaviour specifies such callback. There are no known callbacks, please specify the proper @behaviour and make sure it defines callbacks
  lib/io/stream.ex:2

> warning: got "@impl true" for function exception/1 but no behaviour specifies such callback. There are no known callbacks, please specify the proper @behaviour and make sure it defines callbacks
  lib/io/stream.ex:5

and then these error messages:

`Compilation failed due to warnings while using the --warnings-as-errors option`
`Makefile:74: recipe for target 'lib/elixir/ebin/Elixir.Kernel.beam' failed`
`make: *** [lib/elixir/ebin/Elixir.Kernel.beam] Error 1`

### Expected behavior

If I remove the `+warnings-as_errors` from the `ERLC` in the Makefile, the make completes with all tests passing.

The `+warnings_as_errors` is not in the Makefile for on 1.7.4. I can build 1.7.4 no problem.

Couldn't' see anything in the CHANGELOG that would throw any light on this. Just me?

### PR DESCRIPTION
**Pull request by sneako**
Closes https://github.com/elixir-lang/elixir/issues/8564

This is my first attempt to contribute code to elixir, so please forgive me if this PR is completely naive.

Besides adding the `is_list/1` guards, I have updated the error message to specify that record specifications must use an atom `literal` as the name, to make it clear that the type `atom` is also not valid.

### CODE REVIEW

**Comment by michalmuskala** [comment]
Thank you! :heart:
