### ISSUE TITLE
defstruct does not compile in 1.19

### ISSUE THREAD

**Issue by kmc-firework** [elixir-lang/elixir#14803]
### Elixir and Erlang/OTP versions

Erlang/OTP 28 [erts-16.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.19.0-rc.0 (8d216b8) (compiled with Erlang/OTP 26)

### Operating system

MacOS

### Current behavior

Using the most recent `k8s` package, it fails to compile with the following error:

```
==> k8s Compiling 61 files (.ex) error: undefined function defstruct/1 (there is no such import) │ 12 │ defstruct headers: [], ssl_options: [] │ ^ │ └─ lib/k8s/conn/request_options.ex:12:3: K8s.Conn.RequestOptions (module) == Compilation error in file lib/k8s/conn/request_options.ex == ** (CompileError) lib/k8s/conn/request_options.ex: cannot compile module K8s.Conn.RequestOptions (errors have been logged)
```

### Expected behavior

compiles without issue or a better error message
