### ISSUE TITLE
`rescue e in _` no longer works on v1.5

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#6358]
### Environment

* Elixir & Erlang versions (elixir --version): 1.5.0-rc.1
* Operating system: macOS Sierra

### Current behavior

```elixir
defmodule Foo do
  def hello do
    try do
      Map.fetch!(%{}, :a)
    rescue
      e in _ ->
        IO.inspect e
    end
  end
end
```

```
== Compilation error in file lib/foo.ex ==
** (CompileError) lib/foo.ex:6: unbound variable _
```

### Expected behavior

No compilation error, as on v1.4.

---

Replacement is:

```elixir
try do
  Map.fetch!(%{}, :a)
rescue
  e ->
    IO.inspect e
end
```

I think the old usage should trigger warning.

**Comment by josevalim** [comment]
Fixed in #6360.
