### ISSUE TITLE
Undocumented breaking change with nullary local calls

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12601]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.0-rc.0 (d4d7c8b) (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

This code used to compile with warnings on 1.14
```
defmodule Some do
  def hello do
    some
  end

  def some do
    :some
  end
end
```
on 1.15
```
Compiling 1 file (.ex)
error: undefined variable "some"
  lib/some.ex:3: Some.hello/0


== Compilation error in file lib/some.ex ==
** (CompileError) lib/some.ex: cannot compile module Some (errors have been logged)
```

### Expected behavior

The code should still compile with warnings or if this is an intended breaking change then it should be mentioned in release notes

**Comment by sabiwara** [comment]
Thank you for reporting, this should have been mentioned in release notes indeed.
It is an [intentional](https://github.com/elixir-lang/elixir/pull/12279/files#r1035756729) breaking change but can be disabled by passing the `on_undefined_variable: :warn` [compiler option](https://hexdocs.pm/elixir/main/Code.html#put_compiler_option/2).

**Comment by lukaszsamson** [comment]
How do I enable `on_undefined_variable` in mixfile or `mix compile`? In my case it comes from and old no longer maintained transitive dependencies. In a bigger project it will be troublesome chasing and forking all of them

**Comment by josevalim** [comment]
`Code.compiler_options(on_undefined_variable: :warn)` at the top of your `mix.exs`. :)

**Comment by lukaszsamson** [comment]
@josevalim that's not working
```
mix compile
** (FunctionClauseError) no function clause matching in Code.get_compiler_option/1    
    
    The following arguments were given to Code.get_compiler_option/1:
    
        # 1
        :on_undefined_variable
    
    Attempted function clauses (showing 1 out of 1):
    
        def get_compiler_option(key) when key === :docs or key === :debug_info or key === :ignore_already_consolidated or key === :ignore_module_conflict or key === :relative_paths or key === :warnings_as_errors or key === :no_warn_undefined or key === :tracers or key === :parser_options
    
    (elixir 1.15.0-rc.0) lib/code.ex:1494: Code.get_compiler_option/1
    (elixir 1.15.0-rc.0) lib/code.ex:1475: anonymous fn/2 in Code.compiler_options/1
    (elixir 1.15.0-rc.0) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.15.0-rc.0) lib/code.ex:1474: Code.compiler_options/1
    mix.exs:1: (file)
```
