### ISSUE TITLE
Explorer doesn't compile on 1.20.0-rc.2

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir#15130]
### Elixir and Erlang/OTP versions

Erlang/OTP 28 [erts-16.1] [source] [64-bit] [smp:14:14] [ds:14:14:10] [async-threads:1] [jit]

Elixir 1.20.0-rc.2 (0df45fd) (compiled with Erlang/OTP 28)

### Operating system

Mac OS

### Current behavior

```
4>      error: cannot invoke remote function :lists.member/2 inside a guard
4>      │
4>  219 │                  |> K.or(K.in(n, [:nan, :infinity, :neg_infinity]))
4>      │                            ^
4>      │
4>      └─ lib/explorer/series.ex:219:28: Explorer.Series.is_numeric/1
4>
4>
4> == Compilation error in file lib/explorer/series.ex ==
4> ** (CompileError) lib/explorer/series.ex: cannot compile module Explorer.Series (errors have been logged)
4>     (elixir 1.20.0-rc.2) expanding macro: Kernel.or/2
4>     lib/explorer/series.ex:219: Explorer.Series.is_numeric/1
4>     (elixir 1.20.0-rc.2) expanding macro: Kernel.|>/2
4>     lib/explorer/series.ex:219: Explorer.Series.is_numeric/1
4>     (elixir 1.20.0-rc.2) expanding macro: Kernel.or/2
4>     lib/explorer/series.ex:220: Explorer.Series.is_numeric/1
```

This feels related to https://github.com/elixir-lang/elixir/commit/34a50002f9b3634ed8185efd6a2c65faf21f2c01

### Expected behavior

No failure.

**Comment by LostKobrakai** [comment]
Minimal reproduction:
```elixir
defmodule ReproKernelIn do
  import Kernel, except: [in: 2]

  defguard in_list(a) when Kernel.in(a, [:test])
end
```
